Repository git-big-picture/git-big-picture, pull requests merged in 2021-01, with the labels that each got.

#51 Fix typo "piture"
  .github/dependabot.yml
  .github/workflows/pre-commit-detect-outdated.yml
  .github/workflows/pre-commit-run.yml
  .github/workflows/run-tests.yml
  .pre-commit-config.yaml
  setup.py
Labels: bug

#52 Delete empty requirements.txt
  requirements.txt
Labels: enhancement

#53 More (tiny) flake8 fixes
  .flake8
  git-big-picture
Labels: enhancement

#55 pre-commit: Update isort from v5.6.4 to v5.7.0
  .pre-commit-config.yaml
Labels: enhancement

#57 Fix variable mix-up
  git-big-picture
Labels: bug

#50 Migrate from unmaintained Cram to maintained Scruf
  .github/workflows/run-tests.yml
  .pre-commit-config.yaml
  README.rst
  test.cram
  test.scf
  test_requirements.txt
Labels: enhancement

#64 test.scf: Drop accidental test suite duplication
  test.scf
Labels: enhancement

#65 Fix including commit messages (regression from #48)
  git-big-picture
  test.scf
Labels: bug

#49 Stop leaving temp files behind (finishes up on #25)
  README.rst
  git-big-picture
  test.scf
Labels: bug

#60 Address dead test code
  test.py
Labels: enhancement

#61 Start measuring code coverage
  .coveragerc
  .github/workflows/run-tests.yml
  .gitignore
  run-tests-with-coverage.sh
  test_requirements.txt
Labels: enhancement

#54 Migrate from optparse to argparse
  README.rst
  git-big-picture
Labels: enhancement

#71 Readme: Improve section on people involved
  README.rst
Labels: enhancement

#69 setup.py: Replace ASCII "--" with emdash in description
  setup.py
Labels: enhancement

#70 Handle Ctrl+C gracefully
  git-big-picture
Labels: bug

#68 Improve tempfile prefix
  git-big-picture
Labels: enhancement

#62 Be robust with regard to branch names that contain tick characters ("'") (finishes up on #27)
  git-big-picture
  test.scf
Labels: bug, security

#67 Replace nose by pytest for a test runner (fixes #63)
  README.rst
  run-tests-with-coverage.sh
  test.py
  test_requirements.txt
Labels: enhancement

#59 Support history directions other than upwards (fixes #36, related to #35)
  README.rst
  git-big-picture
  test.scf
Labels: enhancement

#58 Start using standard entry point
  MANIFEST.in
  README.rst
  git_big_picture.py
  git_big_picture/__init__.py
  git_big_picture/__main__.py
  git_big_picture/_main.py
  run-tests-with-coverage.sh
  setup.py
  test.py
  test.scf
Labels: enhancement

#73 Pin and auto-update test requirements
  .github/dependabot.yml
  run-tests-with-coverage.sh
  setup.py
  test_requirements.txt
Labels: enhancement

#66 Start auto-formatting using yapf
  .flake8
  .pre-commit-config.yaml
  .style.yapf
  git_big_picture/_main.py
  setup.py
  test.py
Labels: enhancement

#74 Document changes of release 1.0.0
  README.rst
  git_big_picture/_main.py
Labels: enhancement

#78 remove TODO from README
  README.rst
Labels: enhancement

#83 Extend .gitignore
  .gitignore
Labels: enhancement

#82 Migrate back to Cram
  .cramrc
  .pre-commit-config.yaml
  README.rst
  run-tests-with-coverage.sh
  setup.py
  test.cram
  test_requirements.txt
Labels: enhancement

#80 Improve --help output + make CI prevent copies of --help output from going out-of-sync
  .github/workflows/enforce-copies-of-help-output-in-sync.yml
  README.rst
  git-big-picture.1
  git_big_picture/_main.py
  sync-manpage-with-help-output.sh
  sync-readme-with-help-output.sh
Labels: enhancement

#81 Extend changelog + release 1.1.0
  README.rst
  git_big_picture/_main.py
Labels: enhancement

#86 Fix version number in man page
  git-big-picture.1
Labels: bug

#85 Move Git user setup into Cram tests (to make them work better outside of CI)
  .github/workflows/run-tests.yml
  test.cram
Labels: bug

#87 Document #85, #86, #87 + release 1.1.1
  README.rst
  git-big-picture.1
  git_big_picture/_main.py
Labels: enhancement
